# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.1"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "node1"
  config.vm.network :forwarded_port, guest: 5050, host: 15050 # Mesos master
  config.vm.network :forwarded_port, guest: 8080, host: 18080 # Marathon

  # System provisioning
  config.vm.provision "shell", inline: <<-EOF
    # Network config
    echo "*** NETWORK CONFIG ***"
    sed -i 's/node1//g;s/127.0.0.1\s*$//' /etc/hosts
    echo "192.168.33.10 node1" >>/etc/hosts
    
    # Install Mesos & Marathon
    echo "*** MESOS & MARATHON ***"
    rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    yum -y install mesos marathon
    service mesos-master start
    service mesos-slave start
    service marathon start
    
    # Install Zookeeper
    echo "ZOOKEEPER"
    rpm -Uvh http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm
    yum -y install zookeeper zookeeper-server
    sudo -u zookeeper zookeeper-server-initialize --myid=1
    service zookeeper-server start
  EOF
end
