# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.1"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "node1"
  config.vm.network :forwarded_port, guest: 5050, host: 15050 # Mesos master
  config.vm.network :forwarded_port, guest: 8080, host: 18080 # Marathon

  # Provisioning
  config.vm.provision "shell", path: "01_network.sh"
  config.vm.provision "shell", path: "02_mesos_marathon.sh"
  config.vm.provision "shell", path: "03_zookeeper.sh"
end
